README.md

Show status of this project and show healthy and availability.

Add a workflow status badges

---

backlog.go
examples/wiki/wiki.go
misc.go
misc_test.go
time.go
wiki.go
wiki_test.go

Support backlog API the belows:
* `/api/v2/wikis`
* `/api/v2/wikis/count`
* `/api/v2/wikis/tags`
* `/api/v2/wikis/:wikiID`
and Add unit tests.

Support get wiki API

---

backlog.go
examples/wiki/wiki.go
misc.go
wiki.go
wiki_test.go

Support backlog API the bellows:
* POST `/api/v2/wikis` : create a wiki
* PATCH `/api/v2/wikis/:wikiID` : update a wiki
* DELETE `/api/v2/wikis/:wikiID` : delete a wiki

Support create, update, and delete Wiki API

---

examples/project/project.go
project.go
project_test.go
user.go
user_test.go
wiki.go
wiki_test.go

Support backlog API the bellows:
* GET `/api/v2/projects` : read the list of projects
* GET `/api/v2/projects/:projectID` : read a project
* POST `/api/v2/projects` : create a project
* PATCH `/api/v2/projects/:projectID` : update a project
* DELETE `/api/v2/projects/:projectID` : delete a project

Support create, read, update, and delete project API

---

time_test.go

add unit tests for JSONTime receiver method

Add unit tests for JSONTime

---

.github/FUNDING.yml

add the setting for github sponsor

---

examples/issue/issue.go
go.sum
issue.go
issue_test.go
misc.go
project.go
project_test.go
user.go
user_test.go

* POST `/api/v2/users` : create a user
* PATCH `/api/v2/users/:userID` : update a user
* DELETE `/api/v2/users/:userID` : delete a user
* GET `/api/v2/users/:userID/icon` : download user icon
* GET `/api/v2/users/:userID/activities` : get activities of a user
* GET `/api/v2/users/:userID/stars` : get stars of a user.
* GET `/api/v2/users/:userID/stars/count` : get count of stars
* GET `/api/v2/users/myself/recentlyViewedIssues` : get issues which a user recently viewed
* GET `/api/v2/issues` : get issues

Support user and issue API

---

backlog.go
backlog_test.go
customfield.go
examples/file/file.go
examples/issue/issue.go
examples/project/project.go
examples/space/space.go
examples/webhook/webhook.go
examples/wiki/wiki.go
file.go
file_test.go
go.mod
go.sum
issue.go
issue_test.go
misc.go
misc_test.go
project.go
project_test.go
space.go
space_test.go
time.go
time_test.go
user.go
user_test.go
webhook.go
webhook_test.go
wiki.go
wiki_test.go

Return pointer type from every method due to because reduce memory usage.
Add the "omitempty" option to every field.

Reduce memory usage

---

misc.go
space.go
user.go

A function for downloading files was prepared, but it can be covered by NewRequest() and Do() methods.

Integration of file download process by NewRequest() and Do()

---

backlog.go
file.go
misc.go
project.go

* POST /api/v2/space/attachment: uploads attachments to space

Support uploading multipart file

---

category.go
category_test.go

* GET /api/v2/projects/:projectIdOrKey/categories
* POST /api/v2/projects/:projectIdOrKey/categories
* PATCH /api/v2/projects/:projectIdOrKey/categories/:id
* DELETE /api/v2/projects/:projectIdOrKey/categories/:id

Support categories API

---

backlog.go
issue.go
issue_test.go
issue_type.go
issue_type_test.go
version.go
version_test.go

* GET	/api/v2/projects/:projectIdOrKey/issueTypes
* POST	/api/v2/projects/:projectIdOrKey/issueTypes
* PATCH	/api/v2/projects/:projectIdOrKey/issueTypes/:id
* DELETE	/api/v2/projects/:projectIdOrKey/issueTypes/:id
* GET	/api/v2/projects/:projectIdOrKey/versions
* POST	/api/v2/projects/:projectIdOrKey/versions
* PATCH	/api/v2/projects/:projectIdOrKey/versions/:id
* DELETE	/api/v2/projects/:projectIdOrKey/versions/:id

Support issue type, version API

---

priority.go
priority_test.go
user.go
user_test.go

Support priority API

---

backlog.go
space.go
space_test.go

Support space license API

---

team.go
team_test.go

* GET		/api/v2/teams
* POST		/api/v2/teams
* GET		/api/v2/teams/:teamId
* PATCH		/api/v2/teams/:teamId
* DELETE	/api/v2/teams/:teamId
* GET		/api/v2/teams/:teamId/icon
* GET		/api/v2/projects/:projectIdOrKey/teams
* POST		/api/v2/projects/:projectIdOrKey/teams
* DELETE	/api/v2/projects/:projectIdOrKey/teams

Support team API

---

wiki.go
wiki_test.go

* GET	/api/v2/users/myself/recentlyViewedWikis

Support wiki API

---

customfield.go
customfield_test.go

* GET	/api/v2/projects/:projectIdOrKey/customFields

Support custom field API

---

issue.go
issue_test.go
project_test.go
watching_test.go

* GET	/api/v2/issues/:issueIdOrKey
* PATCH	/api/v2/issues/:issueIdOrKey
* DELETE	/api/v2/issues/:issueIdOrKey
* GET	/api/v2/issues/:issueIdOrKey/comments
* POST	/api/v2/issues/:issueIdOrKey/comments
* GET	/api/v2/issues/:issueIdOrKey/comments/count
* GET	/api/v2/issues/:issueIdOrKey/comments/:commentId
* DELETE	/api/v2/issues/:issueIdOrKey/comments/:commentId
* PATCH	/api/v2/issues/:issueIdOrKey/comments/:commentId
* GET	/api/v2/issues/:issueIdOrKey/comments/:commentId/notifications
* POST	/api/v2/issues/:issueIdOrKey/comments/:commentId/notifications
* GET	/api/v2/issues/:issueIdOrKey/attachments
* GET	/api/v2/issues/:issueIdOrKey/attachments/:attachmentId
* DELETE	/api/v2/issues/:issueIdOrKey/attachments/:attachmentId
* GET …

Support issue API

---

Makefile
README.md

* Add how to contributes this project to README
* Add some test commands to Makefile

For contributors!

---

README.md

There are mistakes.
* rename "api" to "c"
* add `backlog.New(...)` to sample of a downloading file.

update README a little

---

issue.go

Thanks for the useful library.
I have found a typo and fix it.

Fix a typo

---

.github/workflows/lint.yml
.github/workflows/test.yml

- Get the golang version from .tool-versions
- Set timeout-minutes to prevent unintended long execution times

chore: Update GitHub Actions test and lint

---

.golangci.yml
.tool-versions
Makefile
activity_test.go
backlog_test.go
category_test.go
customfield_test.go
file_test.go
go.mod
issue_test.go
issue_type_test.go
priority_test.go
project_test.go
rate_limit_test.go
resolution_test.go
space_test.go
team_test.go
user_test.go
version_test.go
watching_test.go
webhook.go
webhook_test.go
wiki_test.go

- [Upgrade golang version 1.24.2 latest](https://github.com/kenzo0107/backlog/commit/19279f0e975949c3c6825e0bdc7db8ffe09cbad7)
- [fix issues pointed out by golangci-lint](https://github.com/kenzo0107/backlog/commit/b2209b76ba2a07976b6ce0429f352e32a10367f2)

Upgrade golang version to 1 24 2

---

.github/workflows/lint.yml
.github/workflows/test.yml

configure CodeCov on GitHub Actions

---

CLAUDE.md
git.go
git_test.go
pullrequest.go
pullrequest_test.go

- [Add development guide](https://github.com/kenzo0107/backlog/commit/cb94dd95bb0ccdcc07162bff1bfb1011db4eda6c)
- [Add Git repository APIs](https://github.com/kenzo0107/backlog/commit/a7b3f5ea0afeddea84961a1edde9f289b04d3f66)
- [Add Pull Request APIs](https://github.com/kenzo0107/backlog/commit/e87f1811fe8bc0b9e05c9610b32cffaa818cdcb0)

support git repository and pullrequest API
